name: CI-CD pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  CI:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps
      - name: Formatting
        run: npm run format
      - name: Run Playwright E2E tests
        run: npm run test:e2e
